version: "3.7"

services:
  server:
    image: 7_dev_server_image
    container_name: 7_server_dev
    build:
      context: $PWD/server
      dockerfile: $PWD/dockerfiles/server.dockerfile
      target: development
    tty: true
    volumes:
      - $PWD/server:/usr/src/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    environment:
      CARGO_TARGET_DIR: /app/target
      DATABASE_URL: mysql://root:password@db:3306/docker_practice
    command: /bin/sh -c "cargo watch -x run"
    ports:
      - 8080:3000
    networks:
      - local
    depends_on:
      - db

  db:
    # 公式のイメージ
    image: mysql:5.7
    container_name: 7_db_dev
    environment:
      MYSQL_DATABASE: diesel_example
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - "my_db_volume:/var/lib/mysql"
    networks:
      - local

volumes:
  cargo-cache:
  target-cache:
  my_db_volume:


networks:
  local:
