version: "3.7"

services:
  server:
    image: 3_production_server_image
    container_name: 3_server_prod
    build:
      context: $PWD/server
      dockerfile: $PWD/dockerfiles/server.dockerfile
      target: production
    tty: true
